version: '3'

services:
  # MySQL
  db:
    image: mysql:latest
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
    - ./mysql.cnf:/etc/mysql/conf.d/my.cnf
    - ../sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
