DROP DATABASE IF EXISTS `library`;


CREATE DATABASE `library` /*!40100 DEFAULT CHARACTER SET utf8 */ /*!80016 DEFAULT ENCRYPTION='N' */;

CREATE TABLE library.user(
    user_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    user_name VARCHAR(100) NOT NULL,
    books VARCHAR(1000),
    skills VARCHAR(1000)
);
